'use strict';
const fs=require('fs'),assert=require('assert');
const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom');
const path='hamsayeban-android/app/src/main/assets/';
const html=fs.readFileSync(path+'index.html','utf8');
const vc=new VirtualConsole();
vc.on('jsdomError',e=>{throw e});
const loader=new class extends ResourceLoader{
 fetch(url){if(url.endsWith('/localization.js'))return Promise.resolve(fs.readFileSync(path+'localization.js'));return null}
};
async function main(){
 const dom=new JSDOM(html,{url:'https://offline.hamsayeban.test/',runScripts:'dangerously',resources:loader,virtualConsole:vc,pretendToBeVisual:true});
 const w=dom.window,d=w.document;
 await new Promise(resolve=>w.addEventListener('load',resolve,{once:true}));
 w.confirm=()=>true;
 const tick=()=>new Promise(resolve=>setTimeout(resolve,50));
 const q=s=>{const x=d.querySelector(s);assert(x,'Missing '+s);return x};
 const submit=id=>{const e=new w.Event('submit',{bubbles:true,cancelable:true});q(id).dispatchEvent(e)};
 const click=s=>q(s).click();
 click('[data-action="new-building"]');
 q('#building-form [name="name"]').value='مجتمع آزمایشی';
 q('#building-form [name="count"]').value='8';
 submit('#building-form'); await tick();
 let state=JSON.parse(w.localStorage.getItem('hamsayeban-mobile-local-v1'));
 let building=state.buildings.at(-1);
 assert.equal(building.units.length,8);
 click('.sidebar [data-action="nav"][data-page="units"]');
 click('[data-action="view-unit"]');
 click('[data-action="edit-unit"]');
 q('#unit-form [name="owner"]').value='کریمی';
 q('#unit-form [name="occupant"]').value='حسینی';
 q('#unit-form [name="persons"]').value='3';
 q('#unit-form [name="area"]').value='90';
 q('#unit-form [name="floor"]').value='2';
 q('#unit-form [name="occupancy"]').value='tenant';
 submit('#unit-form');await tick();
 state=JSON.parse(w.localStorage.getItem('hamsayeban-mobile-local-v1'));
 building=state.buildings.at(-1);
 assert.equal(building.units.length,8,'capacity fixed');
 assert.equal(building.units[0].owner,'کریمی','owner stored');
 assert.equal(building.units[0].occupant,'حسینی','resident stored');
 assert.equal(building.units[0].floor,2,'floor stored');
 assert.equal(building.units[0].persons,3,'persons stored');
 assert(!d.querySelector('#unit-form'),'edit modal closed');
 console.log('PASS unit edit/save/persistence/capacity');
 click('[data-action="toggle-role"]');
 click('.sidebar [data-action="nav"][data-page="finance"]');
 q('#resident-payment-form [name="amount"]').value='1000000';
 submit('#resident-payment-form');await tick();
 state=JSON.parse(w.localStorage.getItem('hamsayeban-mobile-local-v1'));
 building=state.buildings.at(-1);
 assert.equal(building.pendingPayments?.length,1,'resident submitted payment');
 assert.equal(building.pendingPayments[0].status,'pending');
 assert.equal(building.ledger.length,0,'payment not automatically accepted');
 click('[data-action="toggle-role"]');
 click('.sidebar [data-action="nav"][data-page="finance"]');
 click('[data-action="approve-resident-payment"]');await tick();
 state=JSON.parse(w.localStorage.getItem('hamsayeban-mobile-local-v1'));
 building=state.buildings.at(-1);
 assert.equal(building.pendingPayments[0].status,'approved');
 assert.equal(building.ledger.filter(x=>x.type==='payment').length,1,'ledger credited');
 assert.equal(building.cash.filter(x=>x.source==='payment').length,1,'cash credited');
 console.log('PASS resident payment pending, manager confirmation, finance entries');
 for(const lang of ['en','tr','ar']){
  click('[data-action="nav"][data-page="settings"]');
  click('[data-action="language-select"][data-value="'+lang+'"]');
  await tick();
  const ui=d.querySelector('.page').textContent;
  if(lang==='en'||lang==='tr')assert(!/[\u0600-\u06FF]/u.test(ui),'Non-Latin text in '+lang+' page: '+(ui.match(/[\u0600-\u06FF].{0,30}/u)||[])[0]);
  if(lang==='ar')assert(!/[پچژگکی]/u.test(ui),'Persian-only alphabet in Arabic UI');
  assert.equal(d.documentElement.lang,lang);
  console.log('PASS locale '+lang+' on settings page');
 }
 click('[data-action="nav"][data-page="units"]');
 assert(!/[\u0600-\u06FF]/.test(d.querySelector('.page').textContent)||d.documentElement.lang==='ar');
 console.log('PASS unit names Latin in non-Persian view');
 dom.window.close();
}
main().catch(e=>{console.error(e);process.exit(1)});
